"""
RANDOMNESS / NON-STATIONARITY TESTING (spec Section 43).

This is the module with veto power. Section 43 is unambiguous:

    "If the data behaves close to random and no statistically reliable
     economic edge exists: TRADE = FALSE."

Everything else in this repo estimates probabilities. This measures whether
those probabilities can possibly be better than chance, and hands the
trading engine a single boolean it is not allowed to override.

WHAT WE ARE ACTUALLY TESTING. For Even/Odd to be tradeable, at least one of
these must be false:

  H1  digits are uniform over {0..9}          -> chi-square / G-test
  H2  parity is a fair coin                   -> binomial / Wilson interval
  H3  successive parities are independent     -> runs test, ACF, MI
  H4  the distribution is stationary          -> split-sample, change points

If all four hold, EVEN and ODD are each exactly 0.5, the payout is below
2.0, and expected value is negative on every trade forever. No model in
Section 8-19 can change that; the correct action is to never trade.

HONEST PRIOR (and why the defaults are strict): Deriv's synthetic indices
are generated by an audited CSPRNG. The overwhelmingly likely result is
that every test here passes and the bot waits permanently. That is a
SUCCESSFUL outcome for this module, not a failure of it. Empirical evidence
from a sibling Rise/Fall bot in this account: 1,043 settled trades at 51.68%
win rate, z=1.08, p=0.28 -- indistinguishable from a coin, on the same
instrument family.

DESIGN CONSEQUENCE: these tests are tuned to be hard to fool, not eager to
find structure. alpha defaults to 0.01 (not 0.05), the sample minimums are
large, and a positive finding must ALSO clear an economic effect-size bar
(see EdgeVerdict.economically_relevant) before it counts. A statistically
significant 0.2-point deviation is real and still loses money against a
2.6% house edge.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

from app.statistics.distribution import (
    GoodnessOfFit,
    Interval,
    chi_square_gof,
    g_test,
    norm_sf,
    sidak_alpha,
    wilson_interval,
)


@dataclass(frozen=True)
class RunsTestResult:
    """Wald-Wolfowitz runs test on the parity sequence.

    Detects serial dependence that leaves the MARGINAL rate at 0.5: a
    perfectly alternating EVEN/ODD/EVEN/ODD stream is 50% even, passes every
    frequency test, and is completely predictable. Frequency tests alone
    cannot see it; this can.
    """
    runs: int
    n_even: int
    n_odd: int
    expected_runs: float
    z: float
    p_value: float
    sufficient_sample: bool


def runs_test(parity_sequence: list[int]) -> RunsTestResult:
    n1 = sum(1 for p in parity_sequence if p == 0)   # even
    n2 = len(parity_sequence) - n1
    n = n1 + n2
    if n1 < 10 or n2 < 10:
        return RunsTestResult(0, n1, n2, float("nan"), float("nan"), 1.0, False)
    runs = 1
    for a, b in zip(parity_sequence, parity_sequence[1:]):
        if a != b:
            runs += 1
    expected = 2.0 * n1 * n2 / n + 1.0
    var = (2.0 * n1 * n2 * (2.0 * n1 * n2 - n)) / (n * n * (n - 1.0))
    if var <= 0:
        return RunsTestResult(runs, n1, n2, expected, float("nan"), 1.0, False)
    z = (runs - expected) / math.sqrt(var)
    return RunsTestResult(runs, n1, n2, expected, z, 2.0 * norm_sf(abs(z)), True)


@dataclass(frozen=True)
class AutocorrelationResult:
    lag: int
    coefficient: float
    z: float
    p_value: float
    n: int


def parity_autocorrelation(parity_sequence: list[int], max_lag: int = 10) -> list[AutocorrelationResult]:
    """ACF of the parity series, centred so EVEN=+1 / ODD=-1.

    Under independence each coefficient is ~N(0, 1/n), so z = r*sqrt(n).
    """
    n = len(parity_sequence)
    out: list[AutocorrelationResult] = []
    if n < 100:
        return out
    x = [1.0 if p == 0 else -1.0 for p in parity_sequence]
    mean = sum(x) / n
    centred = [v - mean for v in x]
    denom = sum(v * v for v in centred)
    if denom <= 0:
        return out
    for lag in range(1, max_lag + 1):
        if n - lag < 30:
            break
        num = sum(centred[i] * centred[i + lag] for i in range(n - lag))
        r = num / denom
        z = r * math.sqrt(n)
        out.append(AutocorrelationResult(lag, r, z, 2.0 * norm_sf(abs(z)), n))
    return out


@dataclass(frozen=True)
class StationarityResult:
    """Split-sample stationarity check (Section 43, non-stationarity).

    Splits the history in half and asks whether the two halves look like
    draws from the same digit distribution. A stream that is uniform
    OVERALL but drifts between regimes would pass a pooled chi-square and
    fail this.
    """
    first_half: list[int]
    second_half: list[int]
    statistic: float
    p_value: float
    sufficient_sample: bool


def stationarity_split_test(digits: list[int]) -> StationarityResult:
    n = len(digits)
    if n < 400:
        return StationarityResult([0]*10, [0]*10, 0.0, 1.0, False)
    mid = n // 2
    c1 = [0] * 10
    c2 = [0] * 10
    for d in digits[:mid]:
        c1[d] += 1
    for d in digits[mid:]:
        c2[d] += 1
    # 2x10 contingency chi-square
    n1, n2 = sum(c1), sum(c2)
    total = n1 + n2
    stat = 0.0
    for d in range(10):
        col = c1[d] + c2[d]
        if col == 0:
            continue
        e1 = n1 * col / total
        e2 = n2 * col / total
        if e1 > 0:
            stat += (c1[d] - e1) ** 2 / e1
        if e2 > 0:
            stat += (c2[d] - e2) ** 2 / e2
    from app.statistics.distribution import chi2_sf
    return StationarityResult(c1, c2, stat, chi2_sf(stat, 9), True)


@dataclass
class EdgeVerdict:
    """The single object the trading engine consults for permission.

    `tradeable` is the veto. It is True only when a deviation from
    randomness is BOTH statistically established (after multiple-testing
    correction) AND large enough to matter economically.
    """
    n_samples: int
    alpha: float
    digit_uniformity: GoodnessOfFit | None
    digit_uniformity_g: GoodnessOfFit | None
    parity_interval: Interval | None
    runs: RunsTestResult | None
    autocorrelation: list[AutocorrelationResult] = field(default_factory=list)
    stationarity: StationarityResult | None = None

    break_even_probability: float = 0.5128   # ~1.95x payout; overridden live
    required_margin: float = 0.005

    sufficient_sample: bool = False
    any_significant: bool = False
    economically_relevant: bool = False
    tradeable: bool = False
    reasons: list[str] = field(default_factory=list)

    def summary(self) -> str:
        head = "TRADEABLE" if self.tradeable else "NOT TRADEABLE"
        lines = [f"[{head}] n={self.n_samples} alpha={self.alpha}"]
        lines.extend(f"  - {r}" for r in self.reasons)
        return "\n".join(lines)


class RandomnessMonitor:
    """Runs the full battery and produces an EdgeVerdict.

    MULTIPLE-TESTING DISCIPLINE (Section 40): this battery runs ~14 tests
    (uniformity x2, parity, runs, 10 ACF lags, stationarity) on every
    evaluation. At an uncorrected alpha=0.01 that is a ~13% chance of at
    least one false alarm per evaluation, and the bot evaluates thousands of
    times a day -- it would find "significance" constantly. Every p-value is
    therefore compared against a Sidak-corrected per-test alpha.
    """

    def __init__(self, alpha: float = 0.01, min_samples: int = 2000,
                 required_margin: float = 0.005):
        self.alpha = alpha
        self.min_samples = min_samples
        self.required_margin = required_margin

    def evaluate(self, digits: list[int], *, break_even_probability: float = 0.5128,
                 reference: list[float] | None = None) -> EdgeVerdict:
        n = len(digits)
        parity = [d % 2 for d in digits]
        verdict = EdgeVerdict(
            n_samples=n, alpha=self.alpha,
            digit_uniformity=None, digit_uniformity_g=None,
            parity_interval=None, runs=None,
            break_even_probability=break_even_probability,
            required_margin=self.required_margin,
        )

        if n < self.min_samples:
            verdict.reasons.append(
                f"insufficient sample: {n} < {self.min_samples} required")
            return verdict
        verdict.sufficient_sample = True

        counts = [0] * 10
        for d in digits:
            counts[d] += 1
        verdict.digit_uniformity = chi_square_gof(counts, reference)
        verdict.digit_uniformity_g = g_test(counts, reference)
        even = sum(1 for p in parity if p == 0)
        verdict.parity_interval = wilson_interval(even, n, confidence=1 - self.alpha)
        verdict.runs = runs_test(parity)
        verdict.autocorrelation = parity_autocorrelation(parity)
        verdict.stationarity = stationarity_split_test(digits)

        n_tests = 4 + len(verdict.autocorrelation)
        per_test = sidak_alpha(self.alpha, n_tests)
        verdict.reasons.append(
            f"{n_tests} tests, Sidak per-test alpha={per_test:.5f}")

        significant: list[str] = []
        if verdict.digit_uniformity.p_value < per_test:
            significant.append(
                f"digit distribution non-uniform (chi2={verdict.digit_uniformity.statistic:.1f}, "
                f"p={verdict.digit_uniformity.p_value:.2e}, TVD={verdict.digit_uniformity.total_variation_distance:.4f})")
        if verdict.digit_uniformity_g.p_value < per_test:
            significant.append(f"G-test non-uniform (p={verdict.digit_uniformity_g.p_value:.2e})")
        if verdict.runs.sufficient_sample and verdict.runs.p_value < per_test:
            significant.append(
                f"parity serially dependent (runs z={verdict.runs.z:.2f}, p={verdict.runs.p_value:.2e})")
        for ac in verdict.autocorrelation:
            if ac.p_value < per_test:
                significant.append(f"parity ACF lag {ac.lag} r={ac.coefficient:+.4f} (p={ac.p_value:.2e})")
        if verdict.stationarity and verdict.stationarity.sufficient_sample \
                and verdict.stationarity.p_value < per_test:
            significant.append(f"non-stationary across halves (p={verdict.stationarity.p_value:.2e})")

        verdict.any_significant = bool(significant)
        verdict.reasons.extend(significant if significant else
                               ["no test rejected randomness at the corrected level"])

        # ECONOMIC GATE. Statistical significance is necessary and nowhere
        # near sufficient (Section 40). The parity rate's confidence
        # interval must clear break-even by the required margin on one side
        # -- i.e. we must be confident the achievable rate BEATS the house,
        # not merely that it differs from 0.5.
        pi = verdict.parity_interval
        be = break_even_probability
        even_edge = pi.lower - (be + self.required_margin)
        odd_edge = (1.0 - pi.upper) - (be + self.required_margin)
        best = max(even_edge, odd_edge)
        verdict.economically_relevant = best > 0
        if verdict.economically_relevant:
            side = "EVEN" if even_edge >= odd_edge else "ODD"
            verdict.reasons.append(
                f"economic: {side} interval clears break-even {be:.4f} "
                f"+ margin {self.required_margin:.4f} by {best:.4f}")
        else:
            verdict.reasons.append(
                f"economic: parity CI [{pi.lower:.4f}, {pi.upper:.4f}] does not clear "
                f"break-even {be:.4f} + margin {self.required_margin:.4f} "
                f"(best shortfall {best:.4f})")

        verdict.tradeable = bool(verdict.any_significant and verdict.economically_relevant)
        if not verdict.tradeable:
            verdict.reasons.append(
                "VERDICT: TRADE=FALSE (spec Section 43) -- "
                + ("no established departure from randomness"
                   if not verdict.any_significant
                   else "departure established but too small to beat contract economics"))
        return verdict
